### ISSUE TITLE
Why use MongoDB and not just a json?

### ISSUE THREAD

**Issue by hbontempo-br** [dtinth/todo-actions#55]
I'm sure there is a good reason, but why use a MongoDB instead of a simple json in the repo to keep track of the todos/issues?
I know that the performance is going to possibly be a problem, but it would make this action much easier to setup.

ps: I know this repo is not being actively maintained in the moment, but I like the approach used for solving this problem.

**Comment by dtinth** [comment]
Hello, @hbontempo-br!

I wanted to avoid a race condition where an issue is created twice. That’s why issues and code commits are created in 3 phases. Now I think this is an overengineered solution. :joy:
